language: elixir

cache:
  directories:
    - deps

matrix:
  include:
    - elixir: 1.9
      otp_release: 21.0
    - elixir: 1.9
      otp_release: 22.0.1
sudo: false
env:
  matrix:
    - POXA_REGISTRY_ADAPTER=gproc
before_script:
  - gem install pronto-dialyzer > /dev/null &
  - export PLT_FILENAME=elixir-$TRAVIS_ELIXIR_VERSION-$TRAVIS_OTP_RELEASE.plt
  - wget -O .local.plt https://s3.amazonaws.com/poxa-plt/travis_elixir_plts/$PLT_FILENAME || true
script:
  - mix test --no-start --trace
  - mix test --trace --only integration
  - mix format --check-formatted
  - mix dialyzer -o dialyzer.out && cat dialyzer.out || true
after_script:
  - PULL_REQUEST_ID=$TRAVIS_PULL_REQUEST pronto run -f github_pr -c origin/master
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
